# nginx-graviton-deployment.yaml
# Test deployment for ARM64/Graviton architecture nodes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-graviton
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-graviton
  template:
    metadata:
      labels:
        app: nginx-graviton
    spec:
      # Schedule on Graviton nodes using tolerations and node selector
      tolerations:
        - key: arch-type
          value: graviton
          effect: NoSchedule
      nodeSelector:
        arch-type: graviton
        kubernetes.io/arch: arm64
      containers:
      - name: nginx
        image: nginx:latest  
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"