# nginx-x86-deployment.yaml
# Test deployment for x86/amd64 architecture nodes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-x86
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-x86
  template:
    metadata:
      labels:
        app: nginx-x86
    spec:
      # Schedule on x86 nodes using tolerations and node selector
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
          effect: NoSchedule
        - key: arch-type
          value: x86
          effect: NoSchedule
      nodeSelector:
        karpenter.sh/nodepool: x86-nodepool
        kubernetes.io/arch: amd64
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/nodepool
                operator: In
                values:
                - x86-nodepool
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"