# Example workloads that use different NodePools

---
# GPU Workload - will schedule on GPU nodes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-training-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-training
  template:
    metadata:
      labels:
        app: ml-training
    spec:
      nodeSelector:
        workload-type: gpu
      tolerations:
      - key: nvidia.com/gpu
        operator: Equal
        value: "true"
        effect: NoSchedule
      containers:
      - name: training
        image: nvidia/cuda:11.0-base
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1

---
# High-performance compute workload
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compute-intensive-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: compute-app
  template:
    metadata:
      labels:
        app: compute-app
    spec:
      nodeSelector:
        workload-type: compute-intensive
      containers:
      - name: compute
        image: nginx
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"

---
# Cost-optimized ARM workload
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
        workload-type: cost-optimized
      containers:
      - name: api
        image: nginx:latest
        resources:
          requests:
            cpu: "0.5"
            memory: "1Gi"

---
# Database workload with anti-affinity
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
spec:
  serviceName: postgres
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        suitable-for: databases
      tolerations:
      - key: workload-type
        operator: Equal
        value: database
        effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - postgres
            topologyKey: kubernetes.io/hostname
      containers:
      - name: postgres
        image: postgres:14
        resources:
          requests:
            cpu: "2"
            memory: "8Gi"
